Home page skeleton
sessions-app/sessions-app pull request #19
Opened 2017-07-10 06:28 UTC by mattgfisch

Trello Story: https://trello.com/c/c3LkVUp8

Merging this branch to development will add a home page skeleton that we can work off of. Here is a screenshot of what it looks like:

<img width="1440" alt="screen shot 2017-07-09 at 11 11 35 pm" src="https://user-images.githubusercontent.com/21322741/28005018-31ae36c6-64fd-11e7-9fe5-b209e468d4b8.png">

To accomplish this I:
- Removed the unneeded React component
- Created a page header and a jumbotron (Bootstrap)
- Added custom styling to buttons
- Established a color-scheme

Caveats:
- The hook is just a stub
- Although it was specified in the Acceptance Criteria, there is no logo

Although it would be nice to have the final content for our hook and very nice to have a logo, I think it's a bit early to focus on those things. I'll add creating a logo and polishing the main page content to the tasks we'll complete in the final week before Alpha testing.

2017-07-10 15:19 UTC, mpace965 requested changes
I think the homepage looks really good!

It would also be prudent though to override the bootstrap `$brand` colors like we talked about. [Here](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L7) is a complete listing of them. This would allow you to get rid of some (all?) of the `!important` rules, and will also make further styling easier and more consistent.

Doing this essentially entails redefining the sass variables after you import bootstrap. [This forum post](https://laracasts.com/discuss/channels/elixir/how-to-modify-things-inside-bootstrap-sass/replies/109552)  describes a good method I think.

So, to clarify, I don't think any of the styling needs to change, but try out the variable overriding and see if that cuts down on having to explicitly define a bunch of colors.

2017-07-10 15:19 UTC, mpace965 commented on src/client/views/home.hbs
>  <script src='{{assetPrefix}}/js/hello.js'></script>
Maybe get rid of this script tag too.

2017-07-10 20:59 UTC, mattgfisch commented on src/client/views/home.hbs
>  <script src='{{assetPrefix}}/js/hello.js'></script>
Sounds good! That would be a much cleaner solution and, like you said, would make it easy to implement the color scheme in the future. I'll get rid of the script tag as well and then repush!

2017-07-11 02:07 UTC, mattgfisch commented on src/client/assets/styling/main.scss
> +
I brought in our own variables to take the place of some Bootstrap variables and then used our own variables in areas of our home page where bootstrap doesn't automatically provide styling. I also bring in `overwrites` to overwrite Bootstrap behavior that doesn't rely on variables.

2017-07-11 02:08 UTC, mattgfisch commented on src/client/assets/styling/main.scss
> +
Ultimately some of this content will be refactored to a homepage specific stylesheet, but I'll wait until I work on the Sessions page to do that. That way, I'll know which styles are overlapping and which are specific to each page.

2017-07-11 02:36 UTC, mpace965 approved these changes
Nice, code and site looks very clean!! :100:

2017-07-11 02:37 UTC, mpace965 commented
Don't forget to squash (like I did - :laughing:)

2017-07-11 03:06 UTC, merged