Refactor session state
sessions-app/sessions-app pull request #35
Opened 2017-07-25 07:16 UTC by mpace965

[Trello](https://trello.com/c/EgKkXeab/33-refactor-the-act-of-searching-for-a-track)

* All state lives in `SessionStore`
* `SessionStore` makes its `setState` available to any child component that needs it
* All child componets are just a function of their `props`, and have no state of their own.
* Some light refactoring along the way
* Use es6 export syntax
* Added an alert flash for whenever our request to `/sessions/search-tracks` might fail.
* Also renamed folders that only contained an `index.jsx` to just be `FolderName.jsx` (ex: `ContributionList/index.jsx -> ContributionList.jsx`. This is a pattern we should adopt in the server too. Whenever the single file gets too complex, then break it out into `name/index.js` and e.g. `name/helper.js`.

2017-07-25 07:28 UTC, mpace965 commented
If you want to try out the `AlertFlash`, replace `onSuggestionsFetchRequested` in `ContributionSearch.jsx` with the following definition:

```jsx
const onSuggestionsFetchRequested = (storeSetState) => {
  const choice = (Math.random() > 0.5) ? 0 : 1;
  const errState = [{
    flashMsg: (<p>Spotify search failed. Please contact support.</p>),
    flashType: 'danger',
  }, {
    flashMsg: (<p>Hello there.</p>),
    flashType: 'info',
  }];

  storeSetState(errState[choice]);
};
```

And then just type in the box and you should see the various alerts.

2017-07-25 15:22 UTC, mpace965 commented on src/client/assets/components/Session/ContributionSearch.jsx
> +    .catch((err) => { throw err; });
I kept the axios call here instead of inside of the store. I think it kinda makes sense here, since its very related to the search that this component does. But it doesn't really follow the smart component/dumb component pattern. Let me know what you think.

2017-07-25 15:33 UTC, mpace965 commented on src/client/assets/components/Session/JoinModal.jsx
> +);
These buttons above (L11-L65) could probably be their own components. It seems like a lot of prop validation that we've already done. I think it makes sense just like this too.

2017-07-25 22:03 UTC, mattgfisch commented on src/client/assets/components/Session/ContributionSearch.jsx
> +    .catch((err) => { throw err; });
I think in this case it makes sense since the action is very much tied to the nature of the component. If we get to a point in the future where this same pattern is expressed over many other components then maybe it'd be worth thinking about a refactor, but for now it's the way to go!

2017-07-25 23:16 UTC, mattgfisch requested changes
The restructuring of the file system and migration of state to the parent component looks good! I just ran into a minor bug where the contribute-track-btn's classes become out of step with the `disabled` attribute.

https://www.screencast.com/t/LR5fQWwD4V

2017-07-25 23:16 UTC, mattgfisch commented on src/client/assets/components/Session/JoinModal.jsx
> +    className={contributeBtnClasses(contributions.length)}
Here you also need to pass in the `selectedTrack` so that the classes toggle correctly. When I pulled it down, I ran into an issue where the classes and the attribute `disabled` became out of step. The button was disabled, but had the class `contribute-track-enabled`. 

<img width="868" alt="screen shot 2017-07-25 at 4 03 13 pm" src="https://user-images.githubusercontent.com/21322741/28597524-33d17c4e-7153-11e7-8ca0-c03d9d1bf47c.png">

2017-07-25 23:20 UTC, mattgfisch commented on src/client/assets/components/Session/JoinModal.jsx
> +);
I think it's alright to leave the buttons the way they are since they won't increase in complexity any time in the near future

2017-07-26 01:49 UTC, mpace965 commented
Great catch, not sure how I missed that during manual testing. I think what happened is I got the arguments to the two `classname` methods switched around.

Also caught another bug where the + button could have both the enabled & disabled styling at the same time. This was because the expressions `selected || length < 5` and `!selected || length >= 5` are not mutually exclusive. However,  `selected && length < 5` and `!selected || length >= 5` are mutually exclusive, and I think this captures the behavior we want.

2017-07-26 02:03 UTC, mattgfisch approved these changes

2017-07-26 02:04 UTC, mattgfisch commented
Good catch on those two conditions not being mutually exclusive! 🔨

2017-07-26 02:25 UTC, merged